# Generated by Django 4.1.1 on 2022-11-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.URLField(blank=True),
        ),
    ]
