# Generated by Django 4.1.1 on 2022-10-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_name_alter_amenity_desription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='desription',
            new_name='description',
        ),
    ]
