# Generated by Django 4.1.1 on 2022-10-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_amenities_alter_room_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pet_frienddly',
            new_name='pet_friendly',
        ),
    ]
