# Generated by Django 4.1.1 on 2022-10-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('rooms', 'Rooms'), ('experiences', 'Experiences')], max_length=15),
        ),
    ]
